# Generated by Django 4.1.6 on 2023-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('area', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
