# Generated by Django 4.1.6 on 2023-03-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingmanager',
            name='work_type',
            field=models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20),
        ),
        migrations.AddField(
            model_name='fullstackdeveloper',
            name='work_type',
            field=models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20),
        ),
    ]
