# Generated by Django 4.1.6 on 2023-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_digitalmarketingmanager_work_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMLEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/ai_ml_engineers/')),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_letter', models.TextField()),
                ('work_type', models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/game_developers/')),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_letter', models.TextField()),
                ('work_type', models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MobileAppDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/mobile_app_developers/')),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_letter', models.TextField()),
                ('work_type', models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorBackendEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/senior_backend_engineers/')),
                ('phone_number', models.CharField(max_length=20)),
                ('cover_letter', models.TextField()),
                ('work_type', models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='On-Site', max_length=20)),
            ],
        ),
    ]
