# Generated by Django 4.1.6 on 2023-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_aimlengineer_gamedeveloper_mobileappdeveloper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='work_type',
            field=models.CharField(choices=[('on-site', 'On-Site'), ('remote', 'Remote')], default='on-site', max_length=20, verbose_name='Work Type'),
        ),
    ]
