# Generated by Django 4.1.6 on 2023-02-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contact_delete_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
